summary_statistics_full = [
    [None, 'CDA', 'FLOW_L', 'FLOW_H', 'CDA', 'FLOW_L', 'FLOw_H', 'CDA', 'FLOW_L', 'FLOW_H', ], 
    [None, 'T1 - T20', 'T1 - T20', 'T1 - T20', 'T1 - T10', 'T1 - T10', 'T1 - T10', 'T11 - T20', 'T11 - T20', 'T11 - T20', ], 
    ['Average Price', 
        regress_data_interval[(regress_data_interval['format'] == 'CDA')]['weighted_price'].mean(),
        regress_data_interval[(regress_data_interval['format'] == 'FLOW_L')]['weighted_price'].mean(),
        regress_data_interval[(regress_data_interval['format'] == 'FLOW_H')]['weighted_price'].mean(),
        regress_data_interval[(regress_data_interval['round'] <= (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'CDA')]['weighted_price'].mean(),
        regress_data_interval[(regress_data_interval['round'] <= (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_L')]['weighted_price'].mean(),
        regress_data_interval[(regress_data_interval['round'] <= (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_H')]['weighted_price'].mean(),
        regress_data_interval[(regress_data_interval['round'] > (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'CDA')]['weighted_price'].mean(),
        regress_data_interval[(regress_data_interval['round'] > (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_L')]['weighted_price'].mean(),
        regress_data_interval[(regress_data_interval['round'] > (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_H')]['weighted_price'].mean(),
        ],
    ['', 
        '({})'.format(regress_data_interval[(regress_data_interval['format'] == 'CDA')]['weighted_price'].std()), 
        '({})'.format(regress_data_interval[(regress_data_interval['format'] == 'FLOW_L')]['weighted_price'].std()),
        '({})'.format(regress_data_interval[(regress_data_interval['format'] == 'FLOW_H')]['weighted_price'].std()),
        '({})'.format(regress_data_interval[(regress_data_interval['round'] <= (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'CDA')]['weighted_price'].std()), 
        '({})'.format(regress_data_interval[(regress_data_interval['round'] <= (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_L')]['weighted_price'].std()), 
        '({})'.format(regress_data_interval[(regress_data_interval['round'] <= (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_H')]['weighted_price'].std()),
        '({})'.format(regress_data_interval[(regress_data_interval['round'] > (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'CDA')]['weighted_price'].std()), 
        '({})'.format(regress_data_interval[(regress_data_interval['round'] > (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_L')]['weighted_price'].std()),
        '({})'.format(regress_data_interval[(regress_data_interval['round'] > (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_H')]['weighted_price'].std()),
        ],  
    ['|Price - P_{CE}|', 
        regress_data_interval[(regress_data_interval['format'] == 'CDA')]['price_deviation'].mean(),
        regress_data_interval[(regress_data_interval['format'] == 'FLOW_L')]['price_deviation'].mean(),
        regress_data_interval[(regress_data_interval['format'] == 'FLOW_H')]['price_deviation'].mean(),
        regress_data_interval[(regress_data_interval['round'] <= (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'CDA')]['price_deviation'].mean(),
        regress_data_interval[(regress_data_interval['round'] <= (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_L')]['price_deviation'].mean(),
        regress_data_interval[(regress_data_interval['round'] <= (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_H')]['price_deviation'].mean(),
        regress_data_interval[(regress_data_interval['round'] > (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'CDA')]['price_deviation'].mean(),
        regress_data_interval[(regress_data_interval['round'] > (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_L')]['price_deviation'].mean(),
        regress_data_interval[(regress_data_interval['round'] > (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_H')]['price_deviation'].mean(),
        ], 
    ['|P_{t} - P_{t - 1}|', 
        regress_data_interval[(regress_data_interval['format'] == 'CDA')]['price_change'].abs().mean(),
        regress_data_interval[(regress_data_interval['format'] == 'FLOW_L')]['price_change'].abs().mean(),
        regress_data_interval[(regress_data_interval['format'] == 'FLOW_H')]['price_change'].abs().mean(),
        regress_data_interval[(regress_data_interval['round'] <= (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'CDA')]['price_change'].abs().mean(),
        regress_data_interval[(regress_data_interval['round'] <= (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_L')]['price_change'].abs().mean(),
        regress_data_interval[(regress_data_interval['round'] <= (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_H')]['price_change'].abs().mean(),
        regress_data_interval[(regress_data_interval['round'] > (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'CDA')]['price_change'].abs().mean(),
        regress_data_interval[(regress_data_interval['round'] > (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_L')]['price_change'].abs().mean(),
        regress_data_interval[(regress_data_interval['round'] > (num_rounds - prac_rounds) // 2) & (regress_data_interval['format'] == 'FLOW_H')]['price_change'].abs().mean(),
        ], 
    ['Std(\ln P_{t} - \ln P_{t - 1})', 
        regress_data_period[regress_data_period['format'] == 'CDA']['change_log_wprice'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['change_log_wprice'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['change_log_wprice'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['change_log_wprice'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['change_log_wprice'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['change_log_wprice'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['change_log_wprice'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['change_log_wprice'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['change_log_wprice'].mean(),
        ],
    ['#(P_{t} - P_{t - 1})(raw)', 
        len(flat(delta_prices_cda_full)), 
        len(flat(delta_prices_flow_l_full)),
        len(flat(delta_prices_flow_h_full)),
        len(flat(delta_prices_cda_first)), 
        len(flat(delta_prices_flow_l_first)), 
        len(flat(delta_prices_flow_h_first)),
        len(flat(delta_prices_cda_half)), 
        len(flat(delta_prices_flow_l_half)),
        len(flat(delta_prices_flow_h_half)),
        ], 
   ['PPI',
        liquidity_cda_period[liquidity_cda_period['format'] == 'CDA']['ppi'].mean(), 
        liquidity_flow_period[(liquidity_flow_period['format'] == 'FLOW') & (liquidity_flow_period['group'] <= num_groups_flow_low)]['ppi'].mean(),
        liquidity_flow_period[(liquidity_flow_period['format'] == 'FLOW') & (liquidity_flow_period['group'] > num_groups_flow_low)]['ppi'].mean(),
        liquidity_cda_period[(liquidity_cda_period['format'] == 'CDA') & (liquidity_cda_period['round'] <= (num_rounds - prac_rounds) // 2)]['ppi'].mean(), 
        liquidity_flow_period[(liquidity_flow_period['format'] == 'FLOW') & (liquidity_flow_period['round'] <= (num_rounds - prac_rounds) // 2) & (liquidity_flow_period['group'] <= num_groups_flow_low)]['ppi'].mean(),
        liquidity_flow_period[(liquidity_flow_period['format'] == 'FLOW') & (liquidity_flow_period['round'] <= (num_rounds - prac_rounds) // 2) & (liquidity_flow_period['group'] > num_groups_flow_low)]['ppi'].mean(),
        liquidity_cda_period[(liquidity_cda_period['format'] == 'CDA') & (liquidity_cda_period['round'] > (num_rounds - prac_rounds) // 2)]['ppi'].mean(), 
        liquidity_flow_period[(liquidity_flow_period['format'] == 'FLOW') & (liquidity_flow_period['round'] > (num_rounds - prac_rounds) // 2) & (liquidity_flow_period['group'] <= num_groups_flow_low)]['ppi'].mean(),
        liquidity_flow_period[(liquidity_flow_period['format'] == 'FLOW') & (liquidity_flow_period['round'] > (num_rounds - prac_rounds) // 2) & (liquidity_flow_period['group'] > num_groups_flow_low)]['ppi'].mean(), 
        ],
    ['Total Traded Volume', 
        regress_data_period[regress_data_period[format] == 'CDA']['traded_volume'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['traded_volume'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['traded_volume'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['traded_volume'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['traded_volume'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['traded_volume'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['traded_volume'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['traded_volume'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['traded_volume'].mean(),
        ],  
    ['Traded/CE Quantity (%)', 
        100 * regress_data_period[regress_data_period['format'] == 'CDA']['Traded/CE Quantity'].mean(), 
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_L']['Traded/CE Quantity'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_H']['Traded/CE Quantity'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['Traded/CE Quantity'].mean(), 
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['Traded/CE Quantity'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['Traded/CE Quantity'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['Traded/CE Quantity'].mean(), 
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['Traded/CE Quantity'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['Traded/CE Quantity'].mean(),
        ],
    ['Filled CE Quantity (%)', 
        100 * regress_data_period[regress_data_period['format'] == 'CDA']['filled_contract'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_L']['filled_contract'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_H']['filled_contract'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['filled_contract'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['filled_contract'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['filled_contract'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['filled_contract'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['filled_contract'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['filled_contract'].mean(),
        ],
    ['#Orders', 
        regress_data_period[regress_data_period['format'] == 'CDA']['overall_order_num'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['overall_order_num'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['overall_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['overall_order_num'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['overall_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['overall_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_num'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_num'].mean(),
        ],
    ['Seller', 
        regress_data_period[regress_data_period['format'] == 'CDA']['seller_order_num'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['seller_order_num'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['seller_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_order_num'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_num'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_num'].mean(),
    ], 
    ['Buyer', 
        regress_data_period[regress_data_period['format'] == 'CDA']['buyer_order_num'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['buyer_order_num'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['buyer_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_order_num'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_num'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_num'].mean(),
    ], 
    ['Order Quantity', 
        regress_data_period[regress_data_period['format'] == 'CDA']['overall_order_quantity'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['overall_order_quantity'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['overall_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['overall_order_quantity'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['overall_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['overall_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_quantity'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_quantity'].mean(),
    ],
    ['Seller', 
        regress_data_period[regress_data_period['format'] == 'CDA']['seller_order_quantity'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['seller_order_quantity'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['seller_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_order_quantity'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_quantity'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_quantity'].mean(),
    ], 
    ['Buyer', 
        regress_data_period[regress_data_period['format'] == 'CDA']['buyer_order_quantity'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['buyer_order_quantity'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['buyer_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_order_quantity'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_quantity'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_quantity'].mean(),
    ], 
    ['Order Price', 
        regress_data_period[regress_data_period['format'] == 'CDA']['overall_order_price_low'].mean(), 
        [regress_data_period[regress_data_period['format'] == 'FLOW_L']['overall_order_price_low'].mean(), regress_data_period[regress_data_period['format'] == 'FLOW_L']['overall_order_price_high'].mean()],
        [regress_data_period[regress_data_period['format'] == 'FLOW_H']['overall_order_price_low'].mean(), regress_data_period[regress_data_period['format'] == 'FLOW_H']['overall_order_price_high'].mean()],
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['overall_order_price_low'].mean(), 
        [regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['overall_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['overall_order_price_high'].mean()],
        [regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['overall_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['overall_order_price_high'].mean()],
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_price_low'].mean(), 
        [regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_price_high'].mean()],
        [regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_price_high'].mean()],
    ],
    ['Seller', 
        regress_data_period[regress_data_period['format'] == 'CDA']['seller_order_price_low'].mean(), 
        [regress_data_period[regress_data_period['format'] == 'FLOW_L']['seller_order_price_low'].mean(), regress_data_period[regress_data_period['format'] == 'FLOW_L']['seller_order_price_high'].mean()],
        [regress_data_period[regress_data_period['format'] == 'FLOW_H']['seller_order_price_low'].mean(), regress_data_period[regress_data_period['format'] == 'FLOW_H']['seller_order_price_high'].mean()],
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_order_price_low'].mean(), 
        [regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_order_price_high'].mean()],
        [regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_order_price_high'].mean()],
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_price_low'].mean(), 
        [regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_price_high'].mean()],
        [regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_price_high'].mean()],
    ['Buyer', 
        regress_data_period[regress_data_period['format'] == 'CDA']['buyer_order_price_low'].mean(), 
        [regress_data_period[regress_data_period['format'] == 'FLOW_L']['buyer_order_price_low'].mean(), regress_data_period[regress_data_period['format'] == 'FLOW_L']['buyer_order_price_high'].mean()],
        [regress_data_period[regress_data_period['format'] == 'FLOW_H']['buyer_order_price_low'].mean(), regress_data_period[regress_data_period['format'] == 'FLOW_H']['buyer_order_price_high'].mean()],
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_order_price_low'].mean(), 
        [regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_order_price_high'].mean()],
        [regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_order_price_high'].mean()],
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_price_low'].mean(), 
        [regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_price_high'].mean()],
        [regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_price_high'].mean()],
    ],
    ['Order Max Rate', 
        None,
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['overall_order_rate'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['overall_order_rate'].mean(),
        None, 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['overall_order_rate'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['overall_order_rate'].mean(),
        None, 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_rate'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_rate'].mean(),
    ],
    ['Seller', 
        None,
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['seller_order_rate'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['seller_order_rate'].mean(),
        None, 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_order_rate'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_order_rate'].mean(),
        None, 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_rate'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_rate'].mean(),
    ],
    ['Buyer', 
        None,
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['buyer_order_rate'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['buyer_order_rate'].mean(),
        None, 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_order_rate'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_order_rate'].mean(),
        None, 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_rate'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_rate'].mean(),
    ],
    ['%Order at Max Quantity/Rate', 
        regress_data_period[regress_data_period['format'] == 'CDA']['%max_quantity/rate_orders'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['%max_quantity/rate_orders'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['%max_quantity/rate_orders'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders'].mean(),
    ],
    ['Seller', 
        regress_data_period[regress_data_period['format'] == 'CDA']['%max_quantity/rate_orders_sell'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['%max_quantity/rate_orders_sell'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['%max_quantity/rate_orders_sell'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_sell'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_sell'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_sell'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_sell'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_sell'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_sell'].mean(),
    ],
    ['Buyer', 
        regress_data_period[regress_data_period['format'] == 'CDA']['%max_quantity/rate_orders_buy'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['%max_quantity/rate_orders_buy'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['%max_quantity/rate_orders_buy'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_buy'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_buy'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_buy'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_buy'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_buy'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_buy'].mean(),
    ],
    ['Clearing Rate', 
        None, statistics.mean(clearing_rate_flow_l_full), statistics.mean(clearing_rate_flow_h_full),
        None, statistics.mean(clearing_rate_flow_l_first), statistics.mean(clearing_rate_flow_h_first),
        None, statistics.mean(clearing_rate_flow_half), statistics.mean(clearing_rate_flow_half),
       ], 
    ['', 
        None, '({})'.format(statistics.stdev(clearing_rate_flow_l_full)), '({})'.format(statistics.stdev(clearing_rate_flow_h_full)),
        None, '({})'.format(statistics.stdev(clearing_rate_flow_l_first)), '({})'.format(statistics.stdev(clearing_rate_flow_h_first)),
        None, '({})'.format(statistics.stdev(clearing_rate_flow_l_half)), '({})'.format(statistics.stdev(clearing_rate_flow_h_half)),
        ], 
    ['%No Transactions',
        None,
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['%no_trans'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['%no_trans'].mean(),
        None, 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['%no_trans'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['%no_trans'].mean(),
        None, 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%no_trans'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%no_trans'].mean(),
    ],
    ['Mean Transaction Size', 
        int(statistics.mean(volume_volatility_cda_full)), None, None,
        int(statistics.mean(volume_volatility_cda_first)), None, None,
        int(statistics.mean(volume_volatility_cda_half)), None, None,
        ],
    ['', 
        '({})'.format(statistics.stdev(volume_volatility_cda_full)), None, None,
        '({})'.format(statistics.stdev(volume_volatility_cda_first)), None, None,
        '({})'.format(statistics.stdev(volume_volatility_cda_half)), None, None,
        ],
    ['#Transactions', 
        int(statistics.mean(transaction_number_cda_full)), None, None,
        int(statistics.mean(transaction_number_cda_first)), None, None,
        int(statistics.mean(transaction_number_cda_half)), None, None,
         ],
    ['Realized Surplus (%)', 
        100 * regress_data_period[regress_data_period['format'] == 'CDA']['realized_surplus'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_L']['realized_surplus'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_H']['realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['realized_surplus'].mean(),
        ],
    ['Sellers', 
        100 * regress_data_period[regress_data_period['format'] == 'CDA']['seller_realized_surplus'].mean(), 
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_L']['seller_realized_surplus'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_H']['seller_realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_realized_surplus'].mean(), 
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['seller_realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_realized_surplus'].mean(), 
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_realized_surplus'].mean(),
        ],
    ['Buyers', 
        100 * regress_data_period[regress_data_period['format'] == 'CDA']['buyer_realized_surplus'].mean(), 
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_L']['buyer_realized_surplus'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_H']['buyer_realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_realized_surplus'].mean(), 
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['buyer_realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_realized_surplus'].mean(), 
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_realized_surplus'].mean(),
        ],
    ['Surplus (buy-sell)',
        100 * regress_data_period[regress_data_period['format'] == 'CDA']['gross_norm_diff'].mean(), 
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_L']['gross_norm_diff'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_H']['gross_norm_diff'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['gross_norm_diff'].mean(), 
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['gross_norm_diff'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] <= (num_rounds - prac_rounds) // 2)]['gross_norm_diff'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['gross_norm_diff'].mean(), 
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['gross_norm_diff'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['gross_norm_diff'].mean(),
        ],
    ],
]
