summary_trader_short = [
    [None, 'CDA', 'FLOW_L', 'FLOW_H', 'CDA', 'FLOW_L', 'FLOw_H',], 
    [None, 'T1 - T20', 'T1 - T20', 'T1 - T20', 'T11 - T20', 'T11 - T20', 'T11 - T20', ], 
    ['Number of Orders', 
        regress_data_period[regress_data_period['format'] == 'CDA']['overall_order_num'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['overall_order_num'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['overall_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_num'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_num'].mean(),
        ],
    ['Seller', 
        regress_data_period[regress_data_period['format'] == 'CDA']['seller_order_num'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['seller_order_num'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['seller_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_num'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_num'].mean(),
    ], 
    ['Buyer', 
        regress_data_period[regress_data_period['format'] == 'CDA']['buyer_order_num'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['buyer_order_num'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['buyer_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_num'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_num'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_num'].mean(),
    ], 
    ['Quant. per Order', 
        regress_data_period[regress_data_period['format'] == 'CDA']['overall_order_quantity'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['overall_order_quantity'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['overall_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_quantity'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_quantity'].mean(),
    ],
    ['Seller', 
        regress_data_period[regress_data_period['format'] == 'CDA']['seller_order_quantity'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['seller_order_quantity'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['seller_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_quantity'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_quantity'].mean(),
    ], 
    ['Buyer', 
        regress_data_period[regress_data_period['format'] == 'CDA']['buyer_order_quantity'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['buyer_order_quantity'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['buyer_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_quantity'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_quantity'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_quantity'].mean(),
    ], 
    ['Order Price', 
        regress_data_period[regress_data_period['format'] == 'CDA']['overall_order_price_low'].mean(), 
        [regress_data_period[regress_data_period['format'] == 'FLOW_L']['overall_order_price_low'].mean(), regress_data_period[regress_data_period['format'] == 'FLOW_L']['overall_order_price_high'].mean()],
        [regress_data_period[regress_data_period['format'] == 'FLOW_H']['overall_order_price_low'].mean(), regress_data_period[regress_data_period['format'] == 'FLOW_H']['overall_order_price_high'].mean()],
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_price_low'].mean(), 
        [regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_price_high'].mean()],
        [regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_price_high'].mean()],
    ],
    ['Seller', 
        regress_data_period[regress_data_period['format'] == 'CDA']['seller_order_price_low'].mean(), 
        [regress_data_period[regress_data_period['format'] == 'FLOW_L']['seller_order_price_low'].mean(), regress_data_period[regress_data_period['format'] == 'FLOW_L']['seller_order_price_high'].mean()],
        [regress_data_period[regress_data_period['format'] == 'FLOW_H']['seller_order_price_low'].mean(), regress_data_period[regress_data_period['format'] == 'FLOW_H']['seller_order_price_high'].mean()],
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_price_low'].mean(), 
        [regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_price_high'].mean()],
        [regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_price_high'].mean()],
    ],
    ['Buyer', 
        regress_data_period[regress_data_period['format'] == 'CDA']['buyer_order_price_low'].mean(), 
        [regress_data_period[regress_data_period['format'] == 'FLOW_L']['buyer_order_price_low'].mean(), regress_data_period[regress_data_period['format'] == 'FLOW_L']['buyer_order_price_high'].mean()],
        [regress_data_period[regress_data_period['format'] == 'FLOW_H']['buyer_order_price_low'].mean(), regress_data_period[regress_data_period['format'] == 'FLOW_H']['buyer_order_price_high'].mean()],
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_price_low'].mean(), 
        [regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_price_high'].mean()],
        [regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_price_low'].mean(), regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_price_high'].mean()],
    ],
    ['Order Max Rate', 
        None,
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['overall_order_rate'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['overall_order_rate'].mean(),
        None, 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_rate'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['overall_order_rate'].mean(),
    ],
    ['Seller', 
        None,
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['seller_order_rate'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['seller_order_rate'].mean(),
        None, 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_rate'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['seller_order_rate'].mean(),
    ],
    ['Buyer', 
        None,
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['buyer_order_rate'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['buyer_order_rate'].mean(),
        None, 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_rate'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['buyer_order_rate'].mean(),
    ],
    ['%Order at Max Quantity', 
        regress_data_period[regress_data_period['format'] == 'CDA']['%max_quantity/rate_orders'].mean(), None, None, 
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders'].mean(), None, None, 
    ],
    ['Seller', 
        regress_data_period[regress_data_period['format'] == 'CDA']['%max_quantity/rate_orders_sell'].mean(), None, None,
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_sell'].mean(), None, None,
    ],
    ['Buyer', 
        regress_data_period[regress_data_period['format'] == 'CDA']['%max_quantity/rate_orders_buy'].mean(), None, None,
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_buy'].mean(), None, None,
    ],
    ['%Order at Max Rate', 
        None, 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['%max_quantity/rate_orders'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['%max_quantity/rate_orders'].mean(),
        None,        
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders'].mean(),
    ],
    ['Seller', 
        None,
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['%max_quantity/rate_orders_sell'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['%max_quantity/rate_orders_sell'].mean(),
        None,
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_sell'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_sell'].mean(),
    ],
    ['Buyer', 
        None,
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['%max_quantity/rate_orders_buy'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['%max_quantity/rate_orders_buy'].mean(),
        None, 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_buy'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['round'] > (num_rounds - prac_rounds) // 2)]['%max_quantity/rate_orders_buy'].mean(),
    ],
]