summary_market_short = [
    [None, 'CDA', 'FLOW_L', 'FLOW_H', 'CDA', 'FLOW_L', 'FLOw_H', 'CDA', 'FLOW_L', 'FLOW_H', ], 
    [None, 'T1 - T20', 'T1 - T20', 'T1 - T20', 'T1 - T10', 'T1 - T10', 'T1 - T10', 'T11 - T20', 'T11 - T20', 'T11 - T20', ], 
    ['Clearing Price', 
        regress_data_interval[(regress_data_interval['format'] == 'CDA')]['weighted_price'].mean(),
        regress_data_interval[(regress_data_interval['format'] == 'FLOW_L')]['weighted_price'].mean(),
        regress_data_interval[(regress_data_interval['format'] == 'FLOW_H')]['weighted_price'].mean(),
        regress_data_interval[(regress_data_interval['period'] > (num_periods - prac_periods) // 2) & (regress_data_interval['format'] == 'CDA')]['weighted_price'].mean(),
        regress_data_interval[(regress_data_interval['period'] > (num_periods - prac_periods) // 2) & (regress_data_interval['format'] == 'FLOW_L')]['weighted_price'].mean(),
        regress_data_interval[(regress_data_interval['period'] > (num_periods - prac_periods) // 2) & (regress_data_interval['format'] == 'FLOW_H')]['weighted_price'].mean(),
    ],
    ['Std. Dev.', 
        '({})'.format(regress_data_interval[(regress_data_interval['format'] == 'CDA')]['weighted_price'].std()), 
        '({})'.format(regress_data_interval[(regress_data_interval['format'] == 'FLOW_L')]['weighted_price'].std()),
        '({})'.format(regress_data_interval[(regress_data_interval['format'] == 'FLOW_H')]['weighted_price'].std()),
        '({})'.format(regress_data_interval[(regress_data_interval['period'] > (num_periods - prac_periods) // 2) & (regress_data_interval['format'] == 'CDA')]['weighted_price'].std()), 
        '({})'.format(regress_data_interval[(regress_data_interval['period'] > (num_periods - prac_periods) // 2) & (regress_data_interval['format'] == 'FLOW_L')]['weighted_price'].std()),
        '({})'.format(regress_data_interval[(regress_data_interval['period'] > (num_periods - prac_periods) // 2) & (regress_data_interval['format'] == 'FLOW_H')]['weighted_price'].std()),
    ], 
    ['|P_{t} - P_{t - 1}|', 
        regress_data_interval[(regress_data_interval['format'] == 'CDA')]['price_change'].abs().mean(),
        regress_data_interval[(regress_data_interval['format'] == 'FLOW_L')]['price_change'].abs().mean(),
        regress_data_interval[(regress_data_interval['format'] == 'FLOW_H')]['price_change'].abs().mean(),
        regress_data_interval[(regress_data_interval['period'] > (num_periods - prac_periods) // 2) & (regress_data_interval['format'] == 'CDA')]['price_change'].abs().mean(),
        regress_data_interval[(regress_data_interval['period'] > (num_periods - prac_periods) // 2) & (regress_data_interval['format'] == 'FLOW_L')]['price_change'].abs().mean(),
        regress_data_interval[(regress_data_interval['period'] > (num_periods - prac_periods) // 2) & (regress_data_interval['format'] == 'FLOW_H')]['price_change'].abs().mean(),
        ], 
    ['Std. Dev. of (\ln P_{t} - \ln P_{t - 1})', 
        regress_data_period[regress_data_period['format'] == 'CDA']['change_log_wprice'].mean(), 
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['change_log_wprice'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['change_log_wprice'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['change_log_wprice'].mean(), 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['change_log_wprice'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['change_log_wprice'].mean(),
        ],
    ['PPI',
        liquidity_cda_period[liquidity_cda_period['format'] == 'CDA']['ppi'].mean(), 
        liquidity_flow_period[(liquidity_flow_period['format'] == 'FLOW') & (liquidity_flow_period['group'] <= num_groups_flow30)]['ppi'].mean(),
        liquidity_flow_period[(liquidity_flow_period['format'] == 'FLOW') & (liquidity_flow_period['group'] > num_groups_flow30)]['ppi'].mean(),
        liquidity_cda_period[(liquidity_cda_period['format'] == 'CDA') & (liquidity_cda_period['period'] > (num_periods - prac_periods) // 2)]['ppi'].mean(), 
        liquidity_flow_period[(liquidity_flow_period['format'] == 'FLOW') & (liquidity_flow_period['period'] > (num_periods - prac_periods) // 2) & (liquidity_flow_period['group'] <= num_groups_flow30)]['ppi'].mean(),
        liquidity_flow_period[(liquidity_flow_period['format'] == 'FLOW') & (liquidity_flow_period['period'] > (num_periods - prac_periods) // 2) & (liquidity_flow_period['group'] > num_groups_flow30)]['ppi'].mean(), 
        ],
    ['Traded Volume (shares)', 
        regress_data_period[regress_data_period['format'] == 'CDA']['traded_volume'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['traded_volume'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['traded_volume'].mean(),
        regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['traded_volume'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['traded_volume'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['traded_volume'].mean(),
        ],  
    ['Traded Vol. /Q\_{CE} (%)', 
        100 * regress_data_period[regress_data_period['format'] == 'CDA']['Traded/CE Quantity'].mean(), 
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_L']['Traded/CE Quantity'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_H']['Traded/CE Quantity'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['Traded/CE Quantity'].mean(), 
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['Traded/CE Quantity'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['Traded/CE Quantity'].mean(),
        ],
    ['Filled Contract / Q\_{CE} (%)', 
        100 * regress_data_period[regress_data_period['format'] == 'CDA']['filled_contract'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_L']['filled_contract'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_H']['filled_contract'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['filled_contract'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['filled_contract'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['filled_contract'].mean(),
        ],
    ['Num. of Transactions', 
        int(statistics.mean(transaction_number_cda_all20)), None, None,
        int(statistics.mean(transaction_number_cda_last10)), None, None,
        ],
    ['Mean Transaction Size', 
        int(statistics.mean(volume_volatility_cda_all20)), None, None,
        int(statistics.mean(volume_volatility_cda_last10)), None, None,
        ],
    ['Std. Dev.', 
        '({})'.format(statistics.stdev(volume_volatility_cda_all20)), None, None,
        '({})'.format(statistics.stdev(volume_volatility_cda_last10)), None, None,
        ],
    ['Clearing Rate', 
        None, statistics.mean(clearing_rate_flow_l_all20), statistics.mean(clearing_rate_flow_h_all20),
        None, statistics.mean(clearing_rate_flow_last10), statistics.mean(clearing_rate_flow_last10),
       ], 
    ['Dtd. Dev.', 
        None, '({})'.format(statistics.stdev(clearing_rate_flow_l_all20)), '({})'.format(statistics.stdev(clearing_rate_flow_h_all20)),
        None, '({})'.format(statistics.stdev(clearing_rate_flow_l_last10)), '({})'.format(statistics.stdev(clearing_rate_flow_h_last10)),
        ], 
    ['Time with no FLOW Trans (%)',
        None,
        regress_data_period[regress_data_period['format'] == 'FLOW_L']['%no_trans'].mean(),
        regress_data_period[regress_data_period['format'] == 'FLOW_H']['%no_trans'].mean(),
        None, 
        regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['%no_trans'].mean(),
        regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['%no_trans'].mean(),
    ],
    ['Info. Effic.: |Price - P_{CE}|', 
        regress_data_interval[(regress_data_interval['format'] == 'CDA')]['price_deviation'].mean(),
        regress_data_interval[(regress_data_interval['format'] == 'FLOW_L')]['price_deviation'].mean(),
        regress_data_interval[(regress_data_interval['format'] == 'FLOW_H')]['price_deviation'].mean(),
        regress_data_interval[(regress_data_interval['period'] > (num_periods - prac_periods) // 2) & (regress_data_interval['format'] == 'CDA')]['price_deviation'].mean(),
        regress_data_interval[(regress_data_interval['period'] > (num_periods - prac_periods) // 2) & (regress_data_interval['format'] == 'FLOW_L')]['price_deviation'].mean(),
        regress_data_interval[(regress_data_interval['period'] > (num_periods - prac_periods) // 2) & (regress_data_interval['format'] == 'FLOW_H')]['price_deviation'].mean(),
        ], 
    ['Alloc. Effic.: \Pi / \Pi_{CE} (x100)', 
        100 * regress_data_period[regress_data_period['format'] == 'CDA']['realized_surplus'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_L']['realized_surplus'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_H']['realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['realized_surplus'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['realized_surplus'].mean(),
        ],
    ['\Pi^{buy} / \Pi^{buy}_{CE} - \Pi^{sell} / \Pi^{sell}_{CE}',
        100 * regress_data_period[regress_data_period['format'] == 'CDA']['gross_norm_diff'].mean(), 
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_L']['gross_norm_diff'].mean(),
        100 * regress_data_period[regress_data_period['format'] == 'FLOW_H']['gross_norm_diff'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'CDA') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['gross_norm_diff'].mean(), 
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_L') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['gross_norm_diff'].mean(),
        100 * regress_data_period[(regress_data_period['format'] == 'FLOW_H') & (regress_data_period['period'] > (num_periods - prac_periods) // 2)]['gross_norm_diff'].mean(),
        ],
]